name: Publish to npm

on:
  push:
    branches:
      - main # Trigger workflow when changes are pushed to the main branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the Node.js version your project requires
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Build (if needed)
        run: npm run build # Add this step if your package requires a build step

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
